---
# Common configuration for all profiles
spring:
  config:
    activate:
      on-profile: default
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    properties:
      log4j:
        logger:
          org.apache.kafka: ERROR
          kafka: ERROR

---
# Docker profile (activated with -Dspring.profiles.active=docker)
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092

app:
  watch:
    directory: ./logs
    patterns: ENTRY_CREATE
    processed-files: /app/processed-files/
  kafka:
    topic: logs
    bootstrap-servers: kafka:9092

---
# Local development profile (default)
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:29092



app:
  watch:
    directory: ./logs
    patterns: ENTRY_CREATE
    processed-files: /app/processed-files/
  kafka:
    topic: logs
    bootstrap-servers: localhost:29092
